# Generated by Django 3.1 on 2024-11-06 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendos',
            fields=[
                ('id_arriendo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_arriendo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Arriendos',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('arriendo', 'Arriendo'), ('venta', 'Venta')], max_length=10)),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Registrarme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'registrarme',
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Rol_Usuario',
            },
        ),
        migrations.CreateModel(
            name='SolicitudLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_local', models.CharField(max_length=50)),
                ('patente', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'solicitud_local',
            },
        ),
        migrations.CreateModel(
            name='SolicitudUsuario',
            fields=[
                ('id_solicitud_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=100)),
                ('contraseña', models.CharField(max_length=225)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'solicitud_usuario',
            },
        ),
        migrations.CreateModel(
            name='Tiendas',
            fields=[
                ('id_tienda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tienda', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=225)),
                ('region', models.CharField(choices=[('Arica y Parinacota', 'Arica y Parinacota'), ('Tarapacá', 'Tarapacá'), ('Antofagasta', 'Antofagasta'), ('Atacama', 'Atacama'), ('Coquimbo', 'Coquimbo'), ('Valparaíso', 'Valparaíso'), ('Metropolitana de Santiago', 'Metropolitana de Santiago'), ("Libertador General Bernardo O'Higgins", "Libertador General Bernardo O'Higgins"), ('Maule', 'Maule'), ('Ñuble', 'Ñuble'), ('Biobío', 'Biobío'), ('La Araucanía', 'La Araucanía'), ('Los Ríos', 'Los Ríos'), ('Los Lagos', 'Los Lagos'), ('Aysén del General Carlos Ibáñez del Campo', 'Aysén del General Carlos Ibáñez del Campo'), ('Magallanes y de la Antártica Chilena', 'Magallanes y de la Antártica Chilena')], default='Metropolitana de Santiago', max_length=100)),
                ('estado_suscripcion', models.CharField(choices=[('activa', 'Activa'), ('desactiva', 'Desactiva')], max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Tiendas',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('contraseña', models.CharField(max_length=225)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='UsuarioTienda',
            fields=[
                ('id_usuario_tienda', models.AutoField(primary_key=True, serialize=False)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.rolusuario')),
                ('id_tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.tiendas')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.usuarios')),
            ],
            options={
                'db_table': 'Usuario_Tienda',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.usuarios')),
                ('id_usuario_tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.usuariotienda')),
            ],
            options={
                'db_table': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id_sub', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.tiendas')),
            ],
            options={
                'db_table': 'Suscripcion',
            },
        ),
        migrations.CreateModel(
            name='InventarioArriendo',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, max_length=25, null=True)),
                ('precio_arriendo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_disponible', models.IntegerField()),
                ('talla_producto', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], default='45', max_length=10)),
                ('id_tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.tiendas')),
            ],
            options={
                'db_table': 'InventarioArriendo',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, max_length=25, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_disponible', models.IntegerField()),
                ('talla_producto', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], default='45', max_length=10)),
                ('id_tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.tiendas')),
            ],
            options={
                'db_table': 'Inventario',
            },
        ),
        migrations.CreateModel(
            name='DetallesVenta',
            fields=[
                ('id_detallev', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.inventario')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.ventas')),
            ],
            options={
                'db_table': 'Detalles_Venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleArriendo',
            fields=[
                ('id_detallea', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_arriendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.arriendos')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.inventarioarriendo')),
            ],
            options={
                'db_table': 'Detalle_Arriendo',
            },
        ),
        migrations.CreateModel(
            name='CarritoDeCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda_id', models.IntegerField()),
                ('producto_id', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Carritos de Compras',
            },
        ),
        migrations.CreateModel(
            name='CarritoDeArriendo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda_id', models.IntegerField()),
                ('producto_id', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Carritos de Arriendo',
            },
        ),
        migrations.AddField(
            model_name='arriendos',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.usuarios'),
        ),
        migrations.AddField(
            model_name='arriendos',
            name='id_usuario_tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.usuariotienda'),
        ),
    ]
